config/routes.rb
Rails.application.routes.draw do
  root 'cities#index'

  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    City.create(city_params)
    redirect_to root_path
  end


  private

  def city_params
    params.require(:city).permit(:name, :country, :description)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
<h1>WELCOME FELLOW TRAVELER!</h1>
<br />

<p>Do you want to help other people travel better for less? Share your experiences to help other travellers and turn their dream trip into a reality, save money, or travel the world. Or, if you are looking for tips, advice, and suggestions so you can see more for less and make your dream trip a reality, you are in the right place!</p>

<br />
<hr />
<br />


<% @cities.each do |city| %>

<div>
  <h2><%= city.name %></h2><br /> 
  <i><%= city.country %></i><br /> 
  <p><%= city.description %></p><br />
</div>


<% end %>

app/views/cities/new.html.erb
<br />

<div class="booyah-box col-10 offset-1">
<h1>Enter Your Favorite City in the World</h1>
<%= simple_form_for @city do |f| %>
<%= f.input :name %>
<%= f.input :country %>
<%= f.input :description %>
<br />
<%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WELCOME FELLOW TRAVELER!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <%= link_to 'TRAVELER', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
 
        <%= link_to 'Add a City', new_city_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>




    <%= yield %>
  </body>
</html>